import torch

"DATASET"
DATASET_DIR = r"C:\Users\Hyperbook\Desktop\STUDIA\SEM III\PZ#2\dataset\lofi-dataset"
NUM_BARS= 4
STEPS_PER_BAR = 16
USE_SLIDING_WINDOW = True
STRIDE_IN_BARS = 1
NUM_WORKERS = 0

"MODEL"
INPUT_DIM = 128
EMBEDDING_DIM = 128          
ENCODER_HIDDEN_SIZE = 512
LATENT_DIM = 512
CONDUCTOR_HIDDEN_SIZE = 512 
DECODER_HIDDEN_SIZE = 512    
LSTM_LAYERS = 2 

"VAE PARAMS"
BETA_START = 0.05
BETA_END = 0.05
BETA_ANNEAL_STEPS = 1
BETA_WARMUP_EPOCHS = 0

"""TRAIN"""
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 16
LEARNING_RATE = 3e-7
NUM_EPOCHS = 20

"CHECKPOINTS AND LOGGING"
CHECKPOINT_DIR = "checkpoints/lofi_model"
LOG_DIR = "runs/lofi_model"
LOG_INTERVAL = 100
CHECKPOINT_INTERVAL = 2
